#!/bin/sh
. /tmp/loader

MODE="${1:-unset}"
MAC="${2:-ff:00:00:00:00:00}"		# FIXME! this enforces an invalid mac, see sanitizer_mac()
IP="${3:-127.0.0.1}"
HOST="${4:-unset}"

case "$MAC" in
	*'-'*)
		_log it dhcp_script daemon info "ignore non-ethernet events: $MAC"
		exit 0
	;;
esac

if [ -n "$DNSMASQ_INTERFACE" ]; then
	DEV="$DNSMASQ_INTERFACE"
else
	DEV="$( _net ip2dev $IP )"
	_log it dhcp_script daemon info "guessed dev: '$DEV'"
fi

case "$DEV" in
	'br-mastergate')
		TYPE='roaming'

		case "$MODE" in
			'add')
				echo "$MAC $IP $DNSMASQ_LEASE_EXPIRES" >>"$TMPDIR/roaming_dhcp_worker"
				# recent entries on top ("tac")
				grep -sn '' "$TMPDIR/roaming_dhcp_worker" | sort -rn | cut -d: -f2- >"$TMPDIR/roaming_dhcp"
			;;
			'del')
				sed -i "/^$MAC/d" "$TMPDIR/roaming_dhcp_worker"
				sed -i "/^$MAC/d" "$TMPDIR/roaming_dhcp"
			;;
		esac
	;;
	$WANDEV)
		TYPE='wan'
	;;
	$LANDEV)
		TYPE='lan'

		case "$MODE" in
			'add'|'old')
			;;
		esac
	;;
	$WIFIDEV)
		TYPE='wifi'
	;;
	$LODEV)
		TYPE='loopback'
	;;
	'by-mybridge'|'gateway0')	# just for better logging
		TYPE='batman'
	;;
	*)
		TYPE='unknown'
	;;
esac

if [ "$MODE" = 'old' ]; then
	_log it dhcp_$MODE daemon info "'$MAC' is from '$DEV' = ${TYPE}-DEV HOST: $HOST"
else
	_log it dhcp_$MODE daemon info "'$MAC' is from '$DEV' = ${TYPE}-DEV HOST: $HOST"
fi

true
