#!/bin/sh

_cron_daemon_restart()
{
	local func="cron_daemon_restart"
	local reason="$1"

	_log it $func daemon info "[START] $reason"
	/etc/init.d/*crond* restart
	_log it $func daemon info "[READY]"
}
