#!/bin/sh

_net_isrouter()
{
	local ip="$1"

	# simple way for ensure, that only real nodes (OLSR/Mid) are valid
	ip route | grep -Fq "$ip via "
}

_net_macplus()
{
	local mac="$1"
	local summand="${2:-1}"
	local oldIFS="$IFS"
	local byte6

	IFS=':'
	explode $mac	# 00:11:22:33:44:9a -> 00 11 22 33 44 9a
	IFS="$oldIFS"

	byte6="$6"				# 9a  (hex)
	byte6=$(( 0x$byte6 + summand ))		# 155 (dec)
	byte6=$(( byte6 % 256 ))		# e.g. 256 -> 0
	byte6="$( printf '%02x\n' "$byte6" )"	# 9b  (hex)

	echo "$1:$2:$3:$4:$5:$byte6"
}

_net_both_ipv4_in_same_subnet()
{
	local addr1="${1%/*}"	# e.g. 100.68.255.61/27	-> 100.68.255.61
	local mask1="${1#*/}"	#			-> 27
	local addr2="${2%/*}"	# e.g. 100.64.0.1/10	-> 100.64.0.1
	local mask2="${2#*/}"	#			-> 10
	local s1 s2 mask

	if [ $mask1 -lt $mask2 ]; then
		mask="$( _net cidr2mask "$mask1" )"
	else
		mask="$( _net cidr2mask "$mask2" )"
	fi

	explode $( echo "$addr1 $mask" | tr '.' ' ' )	# e.g. 10 63 12 1   255 255 255 240
	s1="$(( $1 & $5 )) $(( $2 & $6 )) $(( $3 & $7 )) $(( $4 & $8 ))"
	explode $( echo "$addr2 $mask" | tr '.' ' ' )
	s2="$(( $1 & $5 )) $(( $2 & $6 )) $(( $3 & $7 )) $(( $4 & $8 ))"

	test "$s1" = "$s2"
}

_net_get_rxtx()
{
	local dev="$1"
	local line

	while read -r line; do {
		explode $line

		case "$1" in
			"$dev:")
				echo "bytes_rx=$2;bytes_tx=${10};"
				return
			;;
		esac
	} done <'/proc/net/dev'
}

_net_tcp_port_reachable()		# please call with 2>/dev/null otherwise you
{					# always see the 'killed' message from background job
	local funcname='net_tcp_port_reachable'
	local server="$1"		# e.g. 127.0.0.1
	local port="$2"			# e.g. 80
	local check_output="$3"		# pattern or <empty>

	local file="$TMPDIR/$funcname"
	local rc=0
	local pid i

	command -v nc >/dev/null || {
		_log it $funcname daemon info '[ERR] no netcat'
		return 0
	}

	# we can't rely on '-w3' or '-z' because of lobotomized busybox netcat
	( nc "$server" "$port" 2>/dev/null >"$file" || touch "$file.error" ) &
	pid=$!

	if [ -n "$check_output" ]; then
		for i in $( seq 5 -1 1 ); do {
			grep -sq -- "$check_output" "$file" && break
			sleep 1
		} done

		[ $i -gt 0 ] || {
			_log it $funcname daemon info "[ERR] '$( cat "$file" )'"
			rc=1
		}
	else
		i=5
		while [ $i -gt 0 ]; do {
			[ -e "$file.error" ] && {
				rc=1
				break
			}

			sleep 1
			i=$(( i - 1 ))
		} done
	fi

	kill ${pid:-empty_pid} 2>/dev/null
	rm "$file" "$file.error" 2>/dev/null

	return $rc
}

_net_count_wireless()
{
	local wifi_clients_sum=0
	local file clients

	# build during watch_wifistuff()
	for file in /tmp/wifi_hasclients_*; do {
		case "$file" in
			*'_max'|*'_*')
			;;
			*)
				read -r clients <"$file"
				wifi_clients_sum=$(( wifi_clients_sum + clients ))
			;;
		esac
	} done

	echo "$wifi_clients_sum"
}

_net_count_wired()
{
	local funcname='net_count_wired'
	local list_noclients line dev ip mac
	local i=0

	# see cisco_collect() IMPROVE!
	# collect lowercase mac's of cisco routers
	list_noclients="$(
		grep -s ' MAC ' '/tmp/cisco-AP'* | cut -d' ' -f5 | while read -r line; do {
			line="$( _sanitizer run "$line" lowercase )"
			printf '%s' " $line"
		} done
	)"

	# /proc/net/arp is not always correct
	ip neigh show >"/tmp/$funcname"

	while read -r line; do {
		explode $line
		ip="$1"
		dev="$3"
		mac="$5"

		case "$mac" in
			*':'*)
				_list contains_element "$list_noclients" "$mac" && continue
			;;
			*)
				# no valid arp
				continue
			;;
		esac

		case "$ip" in
			*'::'*)
				continue
			;;
		esac

		case "$dev" in
			$LANDEV|$WANDEV)
				# list all wired, which are not OLSR, see olsr_build_tables()
				grep -Fq "REMOTE=$ip;" '/tmp/OLSR/LINKS.sh' || i=$(( i + 1 ))
			;;
		esac
	} done <"/tmp/$funcname" && rm "/tmp/$funcname"

	echo "$i"
}

_net_my_isp()		# TODO: http://www.utrace.de/api.php
{
	local option="$1"
	local cachefile="$TMPDIR/myisp"
	local isp method

	[ "$option" != 'cached' -o ! -e "$cachefile" ] && {
		m1()
		{
			_curl it 'http://www.spyber.com' | grep -F 'My Host :' | cut -d'<' -f1
		}

		m2()
		{
			_curl it 'http://www.whoismyisp.org' | sed -n "/ (ISP) is /s/^.*'\(.*\)'.*/\1/p"
		}

		for method in m1 m2; do {
			isp="$( $method )"
			[ -n "$isp" ] && {
				echo "$isp" >"$cachefile"
				break
			}
		} done
	}

	[ -e "$cachefile" ] && read -r isp <"$cachefile"
	echo "${isp:-unknownISP}"
}

_net_fulltrace()
{
	local destination="$1"
	local ip interface speed output mbit nexthop
	local ip_list=

	if [ -n "$destination" ]; then
		nexthop="$destination"
	else
		# '?' or '10.63.160.161 LAN 4369'
		explode $( _wifi speed cached verbose )
		nexthop="$1"
		interface="$2"
		speed="${3:-0}"
	fi

	[ "$nexthop" = '?' ] && {
		read -r nexthop <'/tmp/GATEWAY_CHECK_RECENT_GATEWAY_IP_ONLY'
	}

	case "$interface" in
		WAN|LAN)
			speed=12500	# 100 mbit FIXME! - not true with a transparent wifi bridge
			ip="$LANADR"
		;;
		*)
			ip="$WIFIADR"
		;;
	esac

	mbit=$(( speed * 8 / 1000 ))
	ip_list="$ip_list $nexthop "
	echo "ip: $ip nexthop: $nexthop interface: $interface speed: $speed kilobyte/s = $mbit megabit/s"

	while true; do {
		if [ "$1" = '?' ]; then
			output='?'
		else
			output="$( _tool remote "$1" speed_nexthop )"
			ip="$1"
		fi

		case "$output" in
			'?'|'')
				echo "ready: '$output' (stop at $ip)"
				return 0
			;;
			*)
				case " $ip_list " in
					" $ip ")
						# avoid loop: maintain list of already asked nodes
						# and abort if the same comes again
						echo "loop/abort: $ip"
						return 1
					;;
				esac

				# 10.63.160.161 LAN 4369
				explode $output
				nexthop="$1"
				interface="$2"
				speed="$3"

				case "$interface" in
					WAN|LAN)
						speed=12500	# 100 mbit FIXME! - not true with a transparent wifi bridge
					;;
				esac

				mbit=$(( speed * 8 / 1000 ))
				ip_list="$ip_list $nexthop "
				echo "ip: $ip nexthop: $nexthop interface: $interface speed: $speed kilobyte/s = $mbit megabit/s"
			;;
		esac
	} done
}

_net_arp_reset()
{
	local mac_wish="$1"	# <empty> = all
	local line mac

	while read -r line; do {
		# 10.63.196.161  0x1  0x6  00:10:75:2d:80:e1  *  eth0.1
		explode $line
		mac="$4"

		_net ismacaddress "$mac" || continue

		[ "$mac_wish" = "$mac" -o -z "$mac_wish" ] && {
			_net arp_permanent "$1" "$mac" "$6" 'reachable'
		}
	} done <'/proc/net/arp'
}

_net_show_traffic()
{
	local iface="$1"
	local interval="${2:-1}"
	local bytes_rx bytes_tx old_rx old_tx diff_rx diff_tx mbit_rx mbit_tx percent_tx percent_rx txt change
	local max_tx=1 max_rx=1

	[ -z "$iface" ] && {
		# default via 10.63.99.61 dev eth0.2  metric 2 onlink
		explode $( ip route list exact '0.0.0.0/0' | head -n1 )
		while test ! "$1" = 'dev' -a -n "$1"; do shift; done
		iface="$2"
	}

	local pre="$( _net dev2name "$iface" )/$iface"

	while true; do {
		eval $( _net get_rxtx "$iface" )	# bytes_rx | bytes_tx

		divisor_valid "$interval" || interval=1
		diff_rx=$(( ( bytes_rx - ${old_rx:-0} ) / interval ))	# divisor_valid
		diff_tx=$(( ( bytes_tx - ${old_tx:-0} ) / interval ))	# divisor_valid
		mbit_rx=$(( diff_rx / 80000 ))
		mbit_tx=$(( diff_tx / 80000 ))		# FIXME for small values, e.g. 0.25mbit show only '0'
		old_rx=$bytes_rx
		old_tx=$bytes_tx

		change=
		test $diff_rx -gt $max_rx -a -n "$txt" && { max_rx=$diff_rx; change='newMAX'; }
		test $diff_tx -gt $max_tx -a -n "$txt" && { max_tx=$diff_tx; change='newMAX'; }
		percent_tx="$( _math percentof $diff_tx $max_tx )"
		percent_rx="$( _math percentof $diff_rx $max_rx )"

		txt="$pre: rx/tx = down/upload: $diff_rx | $diff_tx [bytes/s] = $mbit_rx/$mbit_tx [mbit/s] = ${percent_rx%.*}/${percent_tx%.*}% $change"
		_sanitizer run "$txt" number_humanreadable
		echo

		sleep $interval
	} done
}

_net_get_external_ip()		# FIXME! add IPv6 and rename to 'ip4'
{				# FIXME! add override for 'IPv6 only' and 20 ports IPv4-portfw
	local url_user="$1"
	local ip url
	local url_default="$( uci -q get system.@monitoring[0].url )/getip/"
	local url_fallback1="http://intercity-vpn.de/networks/liszt28/getip/"	# if default is unset
	local url_fallback2='http://api.ipify.org'
	local list_url="$url_user $url_default $url_fallback1 $url_fallback2"
	local timeout=6

	for url in $list_url; do {
		ip="$( _curl it "$url" $timeout )"

		_sanitizer run "$ip" ip4 check && {
			echo "$ip"
			return 0
		}
	} done
}

_net_ping_getlatency()
{
	local server="$1"	# e.g. <ip> or <host>
	local pings="${2:-3}"

	# round-trip min/avg/max = 24.638/24.638/24.638 ms	// busybox
	# or:                      ^^^^^^^^^^^^^^^^^^^^
	# 3 packets transmitted, 0 packets received, 100% packet loss
	#                       ^^^
	# rtt min/avg/max/mdev = 33.415/33.415/33.415/0.000 ms	// debian
	# or: <empty>
	explode $( ping -q -c${pings} -W1 "$server" 2>/dev/null | tail -n1 )

	# bad return on error
	test -n "$4" -a "$4" != '0' &&	{
		# round-trip min/avg/max = 15.887/24.931/42.406 ms
		# -> 15.887/24.931/42.406 -> 15 887 24 931 42 406
		local oldIFS="$IFS"; IFS='[/.]'; explode $4; IFS="$oldIFS"

		# output 'average' round trip time: 24.931 -> 24
		echo "$3"
	}
}

_net_ping6()
{
	local dev="${1:-$LANDEV}"		# or a mac
	local option="${2:-$LANDEV}"		# or dev
	local line mac address

	# e.g. dev = macaddress
	_net dev_is_valid "$dev" || {
		mac="$dev"
		dev="$option"
		line="$( _net mac2linklocal "$mac" )"
		address="${line}%$dev"

		ping6 -c1 $address

		echo "ping6 $address"
		echo "ssh $address"
		echo "curl 'http://[$address]/robots.txt'	# needs v7.37.1+"
		echo "wget -O - 'http://[$address]/robots.txt'"
		echo "wget -O - 'http://[$address]/cgi-bin-tool.sh?OPT=startshell'"
		echo "telnet $address"

		return 0
	}

	# FIXME!
	# ping for ~5 secs and remove myself + double

	# option '-L' ("Suppress loopback of multicast packets") is not supported by busybox
	# ip=$(ping6 -L -c 1 -W 2 ff02::1%$iface | grep "^64 bytes" | head -n1 | cut -d ' ' -f 4 | sed "s/:$/%$iface/") ;echo ${ip:-no_reply}
	# idea: filter out own fe80::address from $dev

	# root@Probenraum:~ ping ff02::1
	# PING ff02::1 (ff02::1): 56 data bytes
	# 64 bytes from ff02::1: seq=0 ttl=64 time=0.481 ms
	# 64 bytes from ff02::1: seq=0 ttl=64 time=0.936 ms (DUP!)
	# 64 bytes from ff02::1: seq=1 ttl=64 time=0.554 ms
	# 64 bytes from ff02::1: seq=1 ttl=64 time=1.371 ms (DUP!)
	#
	# -> look at 'ip neigh'

	# e.g. 64 bytes from fe80::6670:2ff:fed3:240a: seq=0 ttl=64 time=2.187 ms
	ping -6 -c1 "ff02::1%$dev" | grep ^'64 bytes' | cut -d' ' -f4 | while read -r line; do {
		# remove last ":"
		line="$( echo "$line" | sed 's/:$//' )"
		# suppress my own
		ip address show dev "$dev" | grep -q "inet6 $line/64" || echo "$line"
	} done
}

_net_text2port()
{
	local text="$1"
	local position char ascii sum value

	while [ ${position:=1} -le ${#text} ]; do {
		char="$( echo "$text" | cut -b $position )"
		ascii="$( printf '%d' "'$char" )"
		value=$(( ( ascii * 17 ) / 3 ))		# nearly no collisions in testsuite: TODO: where is it?
		sum=$(( ${sum:-1025} + value ))
		position=$(( position + 1 ))
	} done

	[ ${sum:=1025} -gt 65535 ] && sum=65535
	echo "${sum:-1025}"
}

_net_refresh_dnshosts()		# this is mostly for getting recent values from nameservice-plugin of olsr
{
	local funcname='net_refresh_dnshosts'
	local pid cmdline line
	local list_pids="$( pidof dnsmasq )"

	# TODO: has_changed '/var/run/hosts_olsr' || return 0

	for pid in $list_pids; do {
		read -r cmdline <"/proc/$pid/cmdline"

		case "$cmdline" in
			*'fakedns'*)
			;;
			*)
				while read -r line; do {
					case "$line" in
						'PPid:'*)
							explode $line

							# it only works with the 'nobody' dnsmasq,
							# which has PPid = 1
							if [ "$2" = '1' ]; then
								# logging stats
								_log it $funcname daemon info "sending SIGUSR1 and HUP to $pid/nobody"
								kill -SIGUSR1 $pid
								# rereads /etc/hosts + /etc/ethers + /var/run/hosts_olsr
								# and calls dhcp_old via dhcp-script
								kill -HUP $pid

								return 0
							else
								break
							fi
						;;
					esac
				} done <"/proc/$pid/status"
			;;
		esac
	} done
}

_net_dhcp_lease_filename()
{
	local file

	if   [ -e '/tmp/dhcp.leases' ]; then		# openwrt
		file="/tmp/dhcp.leases"
	elif [ -e '/var/run/dhcp.leases' ]; then	# freifunk-firmware
		file="/var/run/dhcp.leases"
	else
		file="$( uci -q get dhcp.@dnsmasq[0].leasefile )"
	fi

	[ -z "$file" -o ! -e "$file" ] && {
		file='/tmp/fake_dhcp_lease_file'
		touch "$file"
	}

	echo "$file"
}

_net_dhcp_lease_show()
{
	cat "$( _net dhcp_lease_filename )"
}

_net_dhcp_lease_remove()
{
	local funcname='net_dhcp_lease_remove'
	local mac="$1"
	local line pid
	local dhcp_lease_file="$( _net dhcp_lease_filename )"
	local tempfile="/tmp/dhcp_leases_$$"

	# typical leasfile:
	# 1397204975 f8:e0:79:de:e9:fc 10.10.12.6 anonymous-lan6-n12 *
	# 1397204779 e4:ce:8f:0e:4f:9e 10.10.12.5 anonymous-lan5-n12 01:e4:ce:8f:0e:4f:9e
	while read -r line; do {
		case "$line" in
			*" $mac "*)
			;;
			*)
				echo "$line"
			;;
		esac
	} done <"$dhcp_lease_file" >"$tempfile"

	mv "$tempfile" "$dhcp_lease_file"

	pid="$( _system get_first_pid dnsmasq )"
	_log it $funcname daemon info "sending SIGUSR1 to pid $pid"
	kill -SIGUSR1 $pid	# stats to syslog

	echo >>$SCHEDULER '/etc/init.d/dnsmasq restart'
}

_net_mac2vendor()
{
	local funcname='net_mac2vendor'
	local oui="$1"					# ab12cd | AB12CD | 1122334455AA | 11-22-33-44-55-aa | 11:22:33:44:55:AA
	local option="$2"				# e.g. 'short'
	local url="http://$MONITORING_SERVERIP/oui"	# see /api.txt

	# OUI = O.rganizationally U.nique I.dentifier

	if   [ ${#oui} -eq 6 -o ${#oui} -eq 12 ]; then
		:
	elif [ ${#oui} -eq 17 ]; then
		oui="$( echo "$oui" | tr -d ':' )"
		oui="$( echo "$oui" | tr -d '-' )"
		[ ${#oui} -eq 12 ] || return 1
	else
		[ ${#oui} -eq 0 ] && return 1
		oui="$( _sanitizer run "$oui" mac hex lowercase length:6 )"
		[ ${#oui} -eq 6 ] || return 1
	fi

	# 112233445566
	case "$oui" in
		'ffffff'|'ffffffffffff')
			echo 'locally_administered (802.11p OCB)'
		;;
		# test 2nd bit of first byte: http://de.wikipedia.org/wiki/MAC-Adresse#Vergabestelle
		# for DEC in $(seq 0 255); do HEX="$( printf "0x%X\n" $DEC )"; test $(( HEX & 2 )) -eq 2 && echo $HEX; done | cut -b4- | sort -u
		?'2'*|?'3'*|?'6'*|?'7'*|?'a'*|?'b'*|?'e'*|?'f'*|?'A'*|?'B'*|?'E'*|?'F'*)
			echo 'locally_administered'
		;;
		*)
			local cache="/tmp/oui/$oui"
			[ -e "$cache" ] || {
				mkdir -p '/tmp/oui'
				url="$url/$( echo "$oui" | cut -b 1,2 )/$( echo "$oui" | cut -b 3,4 )/$( echo "$oui" | cut -b 5,6 )"
				_sanitizer run "$( _curl it "$url" 5 2>/dev/null )" shellsafe >"$cache"

				[ $( _file size "$cache" ) -eq 0 ] && {
					_log it $funcname daemon info "download '$url' failed or empty data"
					rm "$cache"
					return 1
				}
			}

			if [ "$option" = "short" ]; then
				head -n1 "$cache"
			else
				cat "$cache"
			fi
		;;
	esac
}

_net_ip4_is_private()
{
	local ip="$1"		# FIXME! check if valid IPv4

	case "$ip" in
		192.168.*|172.1[6-9].*|172.2[0-9].*|172.3[0-1].*|169.254.*|10.*|127.*)
			return 0		# RFC-1918
		;;
		100.[6-9]*|100.1[0-2]*)		# RFC-6598 / Carrier-Grade NAT = 100.64.0.0/10 ... 100.127.255.254/10
			explode $( echo "$ip" | tr '.' ' ' )
			test $2 -ge 64 -a $2 -le 127
			return $?
		;;
		*)
			return 1
		;;
	esac
}

_net_ip2dns()
{
	local ip="$1"
	local startparse last line error output do_olsr

	# root@box:~ nslookup 10.63.6.3
	# Server:    127.0.0.1			// these 2 lines are
	# Address 1: 127.0.0.1 localhost	// optional
	#
	# Name:      10.63.6.3
	# Address 1: 10.63.6.3 mid1.F36-Dach4900er-MESH		// hostname is missing if lookup fails

	# root@box:~ nslookup 10.63.222.1
	# Server:    (null)
	# Address 1: ::1 localhost
	# Address 2: 127.0.0.1 localhost
	#
	# Name:      10.63.222.1
	# Address 1: 10.63.222.1

	output="$( nslookup "$ip" 2>/dev/null || echo 'ERROR ERROR' )"
	explode $output

	case "$6" in
		*'mywifi'*|*'user-lan'*)
			do_olsr='true'
		;;
		*)
			if   [ "$1" = 'ERROR' ]; then
				do_olsr='true'
				error='true'
			elif _net ip4_is_private "$ip"; then
				do_olsr='true'
			fi
		;;
	esac

	[ -n "$do_olsr" ] && {
		[ -e '/var/run/hosts_olsr' ] && {
			while read -r line; do {
				# 10.63.194.131   mid1.Sommerbar-Kamera   # 10.63.194.161 (mid #1)
				explode $line

				case "$1" in
					"$ip")
						echo "$2"
						return 0
					;;
				esac
			} done <'/var/run/hosts_olsr'
		}

		if [ -n "$error" ]; then
			return 1
		else
			# use nslookup-output
			explode $output
		fi
	}

	while shift; do {
		case "$1" in
			'Name:')
				startparse='true'
			;;
			'Address')
				[ -n "$startparse" ] && {
					if [ -n "$4" ]; then
						echo "$4"
					else
						echo "$3"
					fi

					return 0
				}
			;;
			'')
				echo "$last"
				test "$last" != 'ERROR'
				return $?
			;;
		esac

		last="$1"
	} done

	return 1
}

_net_ismacaddress()
{
	case "$1" in
		[0-9a-f][0-9a-f][:-][0-9a-f][0-9a-f][:-]*)
		;;
		*)
			return 1
		;;
	esac
}

_net_ip2mac()		# works only for local/active IP's, but: maybe we want to "guess" using /etc/ethers...?
{			# TODO: send ping for onehop-neighs?
	local funcname='net_ip2mac'
	local get_ip="$1"
	local option="$2"	# string: 'lazy' (mostly for OLSR-neighs, where total exact match is not important)
	local mac=
	local tempfile="$TMPDIR/$funcname.$$"
	local line ip dev local_ip

	# this can be outdated, see http://www.intercity-vpn.de/files/openwrt/login_error.ejbw.wrong.mac.txt
	[ "$option" = 'lazy' ] && {
		cat "/tmp/IP2MAC_${get_ip}" 2>/dev/null
		return $?
	}

	# get mac from interface
	case "$get_ip" in
		'')
			return 1
		;;
		$WIFIADR)
			read -r mac 2>/dev/null <"/tmp/IP2MAC_${get_ip}" || mac="$( _net dev2mac "$WIFIDEV" )"
		;;
		$LANADR)
			read -r mac 2>/dev/null <"/tmp/IP2MAC_${get_ip}" || mac="$( _net dev2mac "$LANDEV" )"
		;;
		$WANADR)
			read -r mac 2>/dev/null <"/tmp/IP2MAC_${get_ip}" || mac="$( _net dev2mac "$WANDEV" )"
		;;
	esac

	# get mac from arp-cache
	[ -z "$mac" ] && {
		# correct is 'eth0.1'
		#
		# root@box: ip -oneline neigh show to 10.63.155.225
		# 10.63.155.225 dev eth0.1 lladdr b0:48:7a:c5:dc:bc REACHABLE
		# 10.63.155.225 dev wlan0 lladdr b0:48:7a:c5:dc:bc STALE
		#
		# root@box: grep b0:48:7a:c5:dc:bc /proc/net/arp 
		# 10.63.155.193    0x1         0x2         b0:48:7a:c5:dc:bc     *        wlan0
		# 10.63.155.225    0x1         0x2         b0:48:7a:c5:dc:bc     *        eth0.1
		# 10.63.2.37       0x1         0x2         b0:48:7a:c5:dc:bc     *        wlan0
		# 10.63.2.37       0x1         0x2         b0:48:7a:c5:dc:bc     *        eth0.1
		# 10.63.155.225    0x1         0x2         b0:48:7a:c5:dc:bc     *        wlan0
		# 10.63.2.35       0x1         0x2         b0:48:7a:c5:dc:bc     *        eth0.1

		ip -oneline neigh show to "$get_ip" >"$tempfile"	# FIXME! cannot be more than 1 line

		while read -r line; do {
			# /proc/net/arp sometimes shows '00:00:00:00:00:00' but 'ip' has this:
			# 10.63.42.125 dev wlan0 lladdr 64:09:80:7f:48:85 used 0/0/0 probes 6 FAILED
			explode ${line:-unset}
			ip="$1"
			dev="$3"
			mac="$5"

			case "$mac" in
				'00:00:00:00:00:00')
					mac=
					continue
				;;
				'24:a4:2c'*)
					# KOUKAAM / NetIO-230b
					[ -e '/tmp/WATCHDOG_TYPE1' ] || _sanitizer run "$ip-$mac" alphanum >'/tmp/WATCHDOG_TYPE1'
				;;
			esac

			if [ "$ip" = "$get_ip" ]; then
				local_ip="$( _net dev2ip "$dev" )"
				arping -c1 -s "$local_ip" -I "$dev" "$ip" >/dev/null && {
					_sanitizer run "$mac" lowercase >"/tmp/IP2MAC_$get_ip"
					break
				}
			else
				mac=
			fi
		} done <"$tempfile"
		rm "$tempfile"
	}

	# get mac from OLSR-neigh
	if [ -z "$mac" ]; then
		[ -e "/tmp/OLSR/isneigh_$get_ip" ] && {
			mac="$( _tool remote "$get_ip" ip2mac )"
			mac="$( _sanitizer run "$mac" mac )"

			[ -z "$mac" ] && {
				# LuCI-based:
				mac="$( _curl it "http://$get_ip/cgi-bin/luci/freifunk/status" | grep -- '-bssid">' | grep -v '>02:' )"
				mac="$( _sanitizer run "$mac" mac lowercase )"

				[ -z "$mac" ] && {
					# Sven-Ola based:
					mac="$( _curl it "http://$get_ip/cgi-bin-status.html" | grep ^'MAC:' )"
					mac="$( _sanitizer run "$mac" mac lowercase )"
				}
			}
		}

		if [ -n "$mac" ]; then
			echo "$mac" >"/tmp/IP2MAC_$get_ip"
		else
			# translate IPs from local interfaces (which are not in arp-cache), e.g. WIFI-2
			dev="$( ip -oneline address show to "$get_ip" | cut -d' ' -f2 )"
			# dev is empty, when IP is not local
			[ -n "$dev" ] && {
				mac="$( _net dev2mac "$dev" )" && {
					echo "$mac" >"/tmp/IP2MAC_${get_ip}"
				}
			}
		fi
	else
		echo "$mac" >"/tmp/IP2MAC_$get_ip"
	fi

	cat "/tmp/IP2MAC_$get_ip" 2>/dev/null
}

_net_dns2ip()
{
	local dns="$1"
	local go

	# explode $( nslookup host86-139-31-49.range86-139.btcentralplus.com )
	# Server: 127.0.0.1 Address 1: 127.0.0.1 localhost Name: host86-139-31-49.range86-139.btcentralplus.com Address 1: 86.139.31.49 host86-139-31-49.range86-139.btcentralplus.com
	explode $( nslookup "$dns" || echo 'ERROR ERROR' )

	while shift; do {
		case "$1" in
			'ERROR'|'')
				return 1
			;;
			'Name:')
				go='true'
			;;
			'Address:'|'Address')
				[ "$go" = 'true' ] || continue

				# 'Address 1: 84.38.67.43'
				# 'Address 1: 2a02:2e0:3fe:100::8 redirector.heise.de'
				# 'Address 2: 193.99.144.80 redirector.heise.de'
				# 'Address:    193.99.144.80'	// spaces on kernel 2.4
				[ "$1" = 'Address' ] && shift
				shift

				case "$1" in
					*':'*)
						# ignore IPv6
					;;
					*)
						echo "$1"
						return 0
					;;
				esac
			;;
		esac
	} done
}

_net_dev2name()
{
	local funcname='net_dev2name'
	local dev="$1"	# e.g. eth0.2 or pppoe-lan

	cat "/var/run/interfaces/dev2name_$dev" 2>/dev/null || {
		_log it $funcname daemon info "using fallback-parser for '$dev'"

		if _net dev_is_wifi "$dev"; then
			echo 'wifi'
		else
			case "$dev" in
				'pppoe-'*)
					# pppoe-lan -> lan
					echo "${dev#*-}"
				;;
			esac
		fi
	}
}

_net_dev2ip()			# only first ip
{
	local funcname='net_dev2ip'
	local dev="$1"
	local option="$2"	# 'ip'|'mask'|'debug'|'ip_but_noloopback'
	local mode="$3"		# 'CIDR'|'mask'

	local line ip_with_mask key

	[ -z "$dev" ] && return 1

	case "$option" in
		'ip_but_noloopback')
			line="$( ip -oneline -f inet address show dev "$dev" | grep -v 'inet 127\.' )"
		;;
		*)
			line="$( ip -oneline -f inet address show dev "$dev" )"
		;;
	esac

	explode ${line:-is_empty}

	case "$3" in
		'inet')
			key="$5"

			case "$key" in
				brd|scope)
					# e.g.:
					# 6: wlan0    inet 10.63.10.1/8 brd 10.255.255.255 scope global wlan0
					# 7: wlan0-1    inet 10.63.10.1/32 scope global wlan0-1
					ip_with_mask="$4"
				;;
				*)
					# e.g.:
					# 8: ppp0 inet 84.183.156.159 peer 217.0.116.17/32 scope global ppp0
					ip_with_mask="$6"
				;;
			esac
		;;
		*)
			if [ "$option" = 'debug' ];then
				_log it $funcname daemon info "[ERR] dev: $dev line: '$line'"
			else
				if [ $( _system uptime sec ) -lt 120 ]; then
					_log it $funcname daemon info "[ERR] dev: $dev line: '$line'"
				else
					case "$( ip -oneline link show dev "$dev" )" in
						*": $dev@"*)
#							_log it $funcname daemon debug "[OK] ignoring piggyback interface $dev@"
						;;
						*' state DOWN'*)
							_log it $funcname daemon debug "[ERR] dev: $dev state: down"
						;;
						*)
							case "$LANDEV" in
								"$dev")
								;;
								"$dev"*)
									_log it $funcname daemon debug "[OK] ignoring interface $dev (which belongs to lan: $LANDEV)"
									return 1
								;;
							esac

							case "$WANDEV" in
								"$dev")
								;;
								"$dev"*)
									_log it $funcname daemon debug "[OK] ignoring interface $dev (which belongs to wan: $WANDEV)"
									return 1
								;;
							esac

							_log it $funcname daemon alert "[ERR] dev: $dev line: '$line'"
							ip address show dev $dev >>$PERMLOG
						;;
					esac
				fi
			fi

			return 1
		;;
	esac

	case "$option" in
		'mask')
			case "$mode" in
				'CIDR')
					echo "${ip_with_mask%/*}"
				;;
				*)
					_net cidr2mask "${ip_with_mask#*/}"
				;;
			esac
		;;
		*)
			case "$mode" in
				'CIDR')
					echo "${ip_with_mask#*/}"
				;;
				'mask')
					_net cidr2mask "${ip_with_mask#*/}"
				;;
				*)
					echo "${ip_with_mask%/*}"
				;;
			esac
		;;
	esac
}

_net_dev2mac()
{
	local dev="${1:-empty_dev}"
	local line mac

	explode $( ip -oneline link show dev "$dev" )
	line="$*"
	mac="${line#*link/ether }"
	mac=${mac%% *}

	_net ismacaddress "$mac" && echo "$mac"
}

_net_devtype2symbol()
{
	case "$1" in
		'tunnel') printf '%s' '=' ;;
		'wifi') printf '%s' '~' ;;
		'unknown') printf '%s' '?' ;;
		*) printf '%s' '-' ;;
	esac
}

_net_dev_is_valid()
{
	local dev="$1"		# e.g. 'eth0.2'
	local line

	while read -r line; do {
		case "$line" in
			"$dev:"*|" $dev:"*|"  $dev:"*|"   $dev:"*|"    $dev:"*)
				return 0
			;;
		esac
	} done <'/proc/net/dev'

	return 1
}

_net_dev_type()		# out: string, "wifi/tunnel/wire"
{
	local dev="$1"
	local option="$2"	# short
	local out

	if   [ -z "$dev" ]; then
		out='unknown'
	elif _net dev_is_wifi "$dev" ; then
		out='wifi'
	elif _net dev_is_tuntap "$dev" ; then
		out='tunnel'
	else
		out='wire'
	fi

	if [ "$option" = 'short' ]; then
		_net devtype2symbol "$out"
	else
		echo "$out"
	fi
}

_net_dev_is_wifi()
{
	# case " $WIFI_DEVS " in
	# 	*" $dev "*)
	#		// is_wifi
	#	;;
	# esac
	case "$1" in
		br-mastergate)
			return 0	# FIXME/roaming
		;;
	esac

	grep -sq ^".*${1:-empty_devname}:" '/proc/net/wireless'
}

_net_dev_is_tuntap()
{
	local dev="$1"

	case "$dev" in
		'tun'*|'tap'*)
			return 0
		;;
		*)
			[ -d "/etc/tinc/$dev" ] && return 0
		;;
	esac

	return 1
}

_net_ip2dev()		# outputs real devname like 'br0' or 'wlan0-1'
{
	local funcname='net_ip2dev'	# TODO: make use of /tmp/CLIENTS_*?
	local ip="$1"
	local ip_found line devlist dev=

	case "$ip" in
		"$WIFIADR") dev="$WIFIDEV" ;;
		"$LANADR") dev="$LANDEV" ;;
		"$WANADR") dev="$WANDEV" ;;
		"$LOADR") dev="$LODEV" ;;
		*) false ;;
	esac && {
		echo "$dev"
		return 0
	}

	devlist="$( tail -n+3 /proc/net/dev | cut -d':' -f1 )"
	for dev in $devlist; do {
		ip_found="$( _net dev2ip "$dev" )"

		[ "$ip" = "$ip_found" ] && {
			echo "$dev"
			return 0
		}
	} done
	dev=

	while read -r line; do {
		case "$line" in
			"$ip "*)
				# 10.63.61.1  0x1  0x2  66:70:02:f3:90:6c  *  wlan1
				explode $line

				[ "$4" = '00:00:00:00:00:00' ] || {
					_log it $funcname daemon debug "try1: $6 <- $*"
					echo "$6"
					return 0
				}
			;;
		esac
	} done <'/proc/net/arp'

	# FIXME! we can be wrong:
	#
	# root@E2-ayse:~ _net ip2dev 10.63.22.65
	# ip -oneline route get 10.63.22.65
	# explode 10.63.22.65 via 10.63.22.89 dev eth0.2 src 10.63.20.89 \ cache
	#
	# it shows the routing-table (over wire), not the expected way over wifi

	# e.g.
	# 192.168.99.243 dev br-mybridge  src 192.168.99.1 \ cache
	# fe80::221:6aff:fe32:7c1c from :: dev eth0  src fe80::da5d:4cff:fe9c:2f1a  metric 0 \ cache
	explode $( ip -oneline route get "$ip" 2>/dev/null || echo 'ERROR ERROR' )

	while shift; do {
		case "$1" in
			'dev')
				dev="$2"
				# batman/macvlan-hack, maybe unneeded
				[ "$dev" = "gateway0" ] && dev="br-mybridge"
				echo "$dev"

				return 0
			;;
			'ERROR'|'metric'|'cache'|'')
				return 1
			;;
		esac
	} done
}

_net_local_inet_offer()			
{	
	local funcname='net_local_inet_offer'
	local gw=''

	. /lib/functions/network.sh
	network_flush_cache
	network_get_gateway gw 'wan' 0
	test -z "$gw" 
}

_net_mac2ip()		# SENSE: get client-IP from different sources
{
	local mac="$1"
	local funcname="mac2ip"

	# 6 x hex-bytes + 5 x ':' = 17
	[ -z "$mac" -o ${#mac} -ne 17 ] && return 1

	_sanitizer include

	local MAC="$( _sanitizer run "${mac:-unset_mac}" lowercase )"
	local IP=
	local hostname=
	local COUNT=

	try_0()
	{
		case "$MAC" in
			02:00:ca:*|02:00:de:*)
				# we use selfdefined mac's on some batman-nodes, e.g.
				# 02:00:ca:b1:01:11 = node 111 (last 4 digits)
				# 02:00:ca:fe:02:22 = node 222
				# 02:00:ca:ff:00:33 = node  33
				# 02:00:de:ad:01:34 = node 134
				MAC="$( echo "$MAC" | cut -d':' -f5 )$( echo "$MAC" | cut -d':' -f6 )"

				MAC="${MAC#0}"          # e.g. 0002 -> 2
				MAC="${MAC#0}"
				MAC="${MAC#0}"

				IP="192.168.$MAC.1"
			;;
		esac
	}

	try_1()		# is filled during _netfiler_user_add() (macs are lowercase)
	{
		if [ -e "/tmp/MAC2IP_$MAC" ]; then
			read -r IP <"/tmp/MAC2IP_$MAC"
		else
			[ -e "/tmp/NETFILTER/MAC2IP/$MAC" ] && {
				read -r IP <"/tmp/NETFILTER/MAC2IP/$MAC"
			}
		fi
	}

	try_2()		# arp-cache (macs are lowercase)
	{
		local mac ip line

		while read -r line; do {
			explode $line
			ip="$1"
			mac="$( _sanitizer run "$4" lowercase )"

			[ "$MAC" = "$mac" ] && {
				IP="$ip"
				return
			}

		} done <'/proc/net/arp'
	}

	try_3()		# DHCP-leases (macs are lowercase)
	{
		local leasefile="$( _net dhcp_lease_filename )"

		[ -e "$leasefile" ] && {
			IP="$( sed -e "/$MAC/!d" -ne 's/^.* ..:..:..:..:..:.. \([0-9]*\.[0-9]*\.[0-9]*\.[0-9]*\) .*/\1/p' "$leasefile" )"
		}
	}

	try_4()		# /etc/ethers -> /etc/local.hosts (macs are lowercase)
	{
		hostname="$( sed -n "s/^$MAC \(.*\)/\1/p" /etc/ethers 2>/dev/null )"
		[ -n "$hostname" ] && IP="$( sed -n "/$hostname/s/^\([0-9\.]*\) ${hostname}.*/\1/p" /etc/local.hosts )"
	}

	for COUNT in 0 1 2 3 4 ; do {
		try_${COUNT}

		[ -n "$IP" ] && {
			echo "$MAC" >/tmp/IP2MAC_$IP
			echo "$IP"
			return 0
		}
	} done

	_log it $funcname daemon info "could not get ip for mac $MAC"
	return 1
}

_net_mac2hostname ()
{
	local MAC="$1"

	local NAME="$( grep -i $MAC /etc/ethers | sed -n 's/^..:..:..:..:..:.. \(.*\)-.*-.*\..*$/\1/p' )"	# cutting off e.g. "-lan1-n364.domain"
	echo ${NAME:=anonym}
}

_net_mac2dev()
{
	local get_mac="$1"
	local exact="$2"		# e.g. for arp_permanent we need 'br-mybridge' and not 'wlan1'
	local mac dev

	_sanitizer include

	while read -r _ _ _ mac _ dev; do {
		mac="$( _sanitizer run "$mac" lowercase )"

		[ "$get_mac" = "$mac" ] && {
			[ -n "$exact" ] || {
				case "$dev" in
					'br-mybridge'|'gateway0')
						for dev in $WIFI_DEVS; do {
							iw dev "$dev" station get "$mac" 2>/dev/null >/dev/null && {
								break
							}
						} done
					;;
				esac
			}

			echo "$dev"
			return 0
		}

	} done <'/proc/net/arp'

	return 1
}

_net_mac2media()
{
	local MAC="$1"				# ARG1: (string) mac-address
	local SHORT="$2"			# ARG2: (string) keyword "short" (optional)
	local OUT=0				# OUT1: (string) wifi,wire OR ~,-
	local DEV="$( _net mac2dev "$MAC" )"

	  if [ "$DEV" = "$WIFIDEV" ]; then
	  	OUT=wifi
	elif uci get system.@ethers[0].wifi | grep -qi $MAC ; then
		OUT=wifi
	elif grep -sq ^"$( _sanitizer run "$( _net mac2ip $MAC )" escape_dots );" /tmp/CLIENTS_WIFI ; then
		OUT=wifi
	else
		OUT=wire		# fixme! this can also be guessed!
	fi

	[ -n "$SHORT" ] && OUT="$( _net devtype2symbol $DEV )"

	printf '%s' "$OUT"
}

_net_arp_permanent()
{
	local FUNC="net_arp_permanent"
        local IP="$1"
        local MAC="$( _sanitizer run "$2" lowercase )"
        local FORCE="$3"				# or <dev>
	local nudmode="${4:-permanent}"			# or 'reachable'
	local MODE LINE DEV dev_keyword=''

	case "$IP" in
		'100.'*)
			return 0	# ugly: do not for roaming
		;;
	esac

        _log it $FUNC daemon info "IP: '$IP' MAC: '$MAC' FORCE: '$FORCE' nudmode: '$nudmode'"

	# see dhcp-script
	[ "$MAC" = '00:00:00:00:00:00' ] && return 1

	if _net dev_is_valid "$FORCE"; then
		DEV="$FORCE"
		dev_keyword="$DEV (user input)"
	else
		DEV="$( _net mac2dev "$MAC" )"		# fixme! probe up to 3 times?
	fi

	LINE="$( ip neigh show to "$IP" dev "$DEV" 2>/dev/null )"
	echo "$LINE" | grep -Fi -q " $nudmode" && {
		_log it $FUNC daemon debug "[OK] already nud '$nudmode' on dev '$DEV'"
		return 0
	}

	if [ -n "$LINE" ]; then
		MODE='change'
	else
		MODE='add'
	fi

 	if [ -z "$DEV" ]; then
		_log it $FUNC daemon info "not in neigh-list, probing"

 		  if [ "$FORCE" = 'wifi' ]; then
			dev_keyword="wifi (forced)"
			DEV="$WIFIDEV"
 		elif [ "$( _net mac2media $MAC )" = 'wire' ]; then		# why a 2nd try? -> checked: is needed somethimes
			dev_keyword="wire (detected at 2nd try)"
			DEV="$LANDEV"
 		else
			dev_keyword="wifi (defaulting)"
			DEV="$WIFIDEV"
 		fi
 	else
		[ -z "$dev_keyword" ] && dev_keyword="$DEV (autodetected)"
 	fi

	_log it $FUNC daemon info "detected physical-device ${dev_keyword:-unknown}: ip neigh $MODE $IP dev $DEV lladdr $MAC nud $nudmode"
	ip neigh $MODE $IP dev $DEV lladdr $MAC nud "$nudmode" 2>/dev/null || return $?

	[ -e "$TMPDIR/OLSR/fixed_arp_$IP" ] && rm "$TMPDIR/OLSR/fixed_arp_$IP"
	return 0
}

_net_mask2cidr()	# see https://lists.openwrt.org/pipermail/openwrt-devel/2015-June/033540.html
{			# e.g.: 255.255.255.0 -> 24
	local x=${1##*255.}
	local allones=$(( (${#1} - ${#x}) * 2 ))
	local tbl='0^^^128^192^224^240^248^252^254^'
	x=${tbl%%${x%%.*}*}
	echo $(( allones + (${#x}/4) ))
}

_net_cidr2mask()	# OUT1: string
{
	local o

	case "$1" in
		31) o=255.255.255.254 ;;
		30) o=255.255.255.252 ;;
		29) o=255.255.255.248 ;;
		28) o=255.255.255.240 ;;
		27) o=255.255.255.224 ;;
		26) o=255.255.255.192 ;;
		25) o=255.255.255.128 ;;
		24) o=255.255.255.0 ;;
		23) o=255.255.254.0 ;;
		22) o=255.255.252.0 ;;
		21) o=255.255.248.0 ;;
		20) o=255.255.240.0 ;;
		19) o=255.255.224.0 ;;
		18) o=255.255.192.0 ;;
		17) o=255.255.128.0 ;;
		16) o=255.255.0.0 ;;
		15) o=255.254.0.0 ;;
		14) o=255.252.0.0 ;;
		13) o=255.248.0.0 ;;
		12) o=255.240.0.0 ;;
		11) o=255.224.0.0 ;;
		10) o=255.192.0.0 ;;
		 9) o=255.128.0.0 ;;
		 8) o=255.0.0.0 ;;
		 7) o=254.0.0.0 ;;
		 6) o=252.0.0.0 ;;
		 5) o=248.0.0.0 ;;
		 4) o=240.0.0.0 ;;
		 3) o=224.0.0.0 ;;
		 2) o=192.0.0.0 ;;
		 1) o=128.0.0.0 ;;
		 *) o=255.255.255.255 ;;
	esac

	printf '%s' "$o"
}

_net_active_ap_devices()	# TODO: add linefeed, so 'read X <FILE' will return 0
{
	local dev

	grep ^'interface=' /var/run/hostapd-phy[0-3].conf | cut -d'=' -f2 | while read -r dev; do printf '%s' " $dev "; done
}
