#!/bin/sh /etc/rc.common 

START=12 

unixtime_from_newest_file_on_disk()
{
	local dir file

	find /etc -type d | while read -r dir; do
		file="$dir/$( ls -1t "$dir" | head -n1 )"
		date -r "$file" +%s
	done | sort -nr | head -n1
}

boot() 
{
	# migrate whole olsr1-network from 'etx_ff' -> 'etx_ffeth'
	# see: https://lists.olsr.org/pipermail/olsr-dev/2012-June/005734.html
	#
	# at this stage we have a valid date from init.d/boot or init.d/sysfixtime
	# (filedate of the newest file on disk) if not - get&set it now

	local year="$( date +%Y )"
	local olsrd_metric="$( uci -q get 'olsrd.@olsrd[0].LinkQualityAlgorithm' )"
	local olsrd_metric_wish='etx_ffeth'

	# e.g. old firmware, where we dont have init.d/sysfixtime
	[ $year -lt 2015 ] && {
		date -s @$( unixtime_from_newest_file_on_disk )
		year="$( date +%Y )"
	}

	[ $year -eq 2016 -a "$olsrd_metric" = 'etx_ff' ] && {
		. /tmp/loader

		_log it switch_olsr_metric daemon alert "hard switch to $olsrd_metric_wish"
		uci set olsrd.@olsrd[0].LinkQualityAlgorithm="$olsrd_metric_wish"
		uci commit olsrd
	}
}

