#!/bin/sh /etc/rc.common

START=41

# todo:
# with/without OLSR on all interfaces? or specific interfaces?

boot()
{
    .  /tmp/loader

    if [ $( _system uptime sec ) -lt 60 ]; then
        if [ -e "/www/NETPARAM" ]; then
            cp "/www/NETPARAM" "/tmp/NETPARAM"
        else
            sleep 30        # fixme! ifstatus wlanadhoc empty, needs about 18 sec till OK on 1043ND
        fi
    else
        HASH_OLD="$( _file hash '/tmp/NETPARAM' )"
        _net build_netparams

        if [ -e "/www/NETPARAM" ]; then
            . '/tmp/NETPARAM'
            grep -q ^"WIFIDEV=$WIFIDEV"$ '/www/NETPARAM' || {
                _log do earlyboot_netparam daemon alert "stored new version, now with WIFIDEV='$WIFIDEV'"
                cp '/tmp/NETPARAM' '/www/NETPARAM'
            }
        else
            _log do earlyboot_netparam daemon alert "stored initial version, WIFIDEV='$WIFIDEV'"
            cp '/tmp/NETPARAM' '/www/NETPARAM'
        fi
    fi

    HASH_NEW="$( _file hash /tmp/NETPARAM )"
    [ "$HASH_OLD" = "$HASH_NEW" ] || {
    /etc/kalua_init         # this includes a static version of NETPARAM
}
