#!/bin/sh /etc/rc.common

START=70

start() {
    [ -n "$FAILSAFE" ] && exit

    . /tmp/loader

	[ -e "/etc/init.d/apply_profile" ] || {
		[ "$( _firmware updatemode )" = "testing" ] && {
			_firmware update_pmu
		}
	}

    # write latlong into file 
    [ -n "$( uci -q get system.@system[0].latitude )" ] && {
        echo "$( uci -q get system.@system[0].latitude ),$( uci -q get system.@system[0].longitude )">/var/run/latlon.txt
    }

	# register first time
	/usr/sbin/cron.registrator_client.sh
	# draw on map first time
	/usr/sbin/owm.lua
}
