#!/bin/sh

START=70

[ -n "$FAILSAFE" ] && exit

start() {
    . /tmp/loader
	[ -e "/etc/init.d/apply_profile" ] || {
		[ "$( _firmware updatemode )" = "testing" ] && {
			_firmware update_pmu
		}
	}

	# register first time
	/usr/sbin/cron.registrator_client.sh
	# draw on map first time
	/usr/sbin/owm.lua
}
