#!/bin/sh
# shellcheck disable=SC2154

. /lib/functions.sh
. /lib/netifd/netifd-proto.sh


#fixme
eval "$@"

[ -n "$dev" ] || {
	logger -t "vtun-up" -p "user.error" "error: no device"
	exit 1
}
ip link set dev "$dev" up

proto_init_update "$dev" 1

eval "$(ipcalc.sh "$address" "$netmask")" && proto_add_ipv4_address "$IP" "$PREFIX" "$BROADCAST"

# fixme
#[ -n "$gw" ] && {
#	proto_add_ipv4_route ${NETWORK} ${PREFIX} ${gw}
#}

proto_add_data
json_add_string server "$server"
json_add_string port "$port"
proto_close_data

proto_send_update "$config"
exit 0
# vim: set filetype=sh ai noet ts=4 sw=4 sts=4 :
