#!/bin/sh

logger -t "vtun-up" "params: $@"

eval "$@"

defaultroute=1

[ -n "$dev" ] || {
	logger -t "vtun-up" -p "user.error" "error: no device"
	exit 1
}

ip link set dev "$dev" up
ip link set dev "$dev" mtu "${mtu}"
. /lib/netifd/netifd-proto.sh
proto_init_update "$dev" 1 1
proto_set_keep 1

for address in ${addresses}; do
  logger -t "vtun-up" "addr: $address"

  case "${address}" in
      *.*/*)
	 ip a add dev "$dev" "${address}"
         proto_add_ipv4_address "${address%%/*}" "${address##*/}"
      ;;
      *.*)
	ip a add dev "$dev" "${address}"
        proto_add_ipv4_address "${address%%/*}" "32"
      ;;
  esac
done


proto_send_update "$config"
# set default route
[ -n "$defaultroute" ] && {
	proto_add_ipv4_route "0.0.0.0" "0" "$gw" "0.0.0.0/0" "$METRIC"
}

proto_send_update "$config"

exit 0
