#!/bin/sh
# shellcheck disable=SC2154

eval "$@"

[ -n "$dev" ] || {
	exit 1
}

/sbin/ip link set dev "$dev" down

. /lib/netifd/netifd-proto.sh

proto_init_update "$dev" 0
proto_send_update "$config"

exit 0
# vim: set filetype=sh ai noet ts=4 sw=4 sts=4 :
