#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

validate_meshnode_section()
{
	uci_validate_section meshnode settings "${1}" \
		'enabled:bool' \
		'hostname:string' \
		'ip6prefix:cidr6' \
		'nodenumber:uinteger'
}

validate_ether_section()
{
	uci_validate_section meshnode ether "${1}" \
		'enabled:bool' \
		'device:string' \
		'olsr_mesh:bool' 
}

validate_wifi_section()
{
	uci_validate_section meshnode wifi "${1}" \
		'enabled:bool' \
		'idx:uinteger' \
		'device:string' \
		'olsr_mesh:bool' \
		'vap:bool' 
}

start_apply_profile() {
	enabled=$(uci_get meshnode settings enabled "0")
	[ "$enabled" == "0" ] && return
	config_load meshnode
	config_foreach system_config system
	/usr/sbin/apply_profile
	uci_set meshnode settings enabled 0
	uci_commit meshnode
}

reload_service() {
	logger -s -t apply_profile_init "Reload Service"
	start_apply_profile
}

service_triggers()
{
	procd_open_trigger
	procd_add_config_trigger "config.change" meshnode /etc/init.d/apply_profile reload
	procd_close_trigger

	procd_open_validate
	validate_meshnode_section
	validate_ether_section
	validate_wifi_section
	procd_close_validate
}

start_service() {
	logger -s -t apply_profile_init "Start Service"
	procd_set_param watch meshnode
	start_apply_profile
}
