#!/bin/sh /etc/rc.common

START=00

boot()
{
	local line unixtime reason
	local crashlog='/sys/kernel/debug/crashlog'
	PERMLOG='/www/everlasting_syslog.txt'		# FIXME! later known via loader

	export TZ="$( uci -q get system.@system[0].timezone )"
	# https://lists.openwrt.org/pipermail/openwrt-devel/2014-January/023196.html
	if   [ -e '/dev/rtc0' ]; then
		# root@CubieNAS:~ :) hwclock -r -f /dev/rtc0
		# Mon Nov  7 12:59:49 2016  0.000000 seconds
		set -- $( hwclock -r -f '/dev/rtc0' )
		unixtime="$( _system date 2unixtime "$1 $2 $3 $4 $5" )"
	elif [ -e "$PERMLOG" ]; then
		unixtime="$( date +%s -r "$PERMLOG" )"
	elif [ -e '/www/switch.txt' ]; then
		unixtime="$( date +%s -r '/www/switch.txt' )"
	else
		unixtime="$( date +%s -r '/etc/banner' )"	# build-date
	fi
	date -s @$(( unixtime + 30 ))

	reason_long()
	{
		local reason="$1"
		local reason_long

		reason_long="$( grep "reason=$reason " '/etc/kalua/system' | cut -d')' -f1 | cut -d'|' -f2 )"
		set -- $reason_long

		echo "${1:-unknown_reason}"
	}

	[ -e '/www/CRASHLOG_WORKS' ] || {
		grep -sq 'Modules:' "$crashlog" && touch '/www/CRASHLOG_WORKS'
	}

	if [ -e '/www/CRASHLOG_WORKS' ]; then
		if line="$( grep -s ' ux.,' "$crashlog" )"; then			# see system_crashreboot()
			# <4>[29071.240000] CPU: 0 PID: 7201 Comm: ux0,1388632927, Not tainted 3.10.24 #18
			# <4>[ 9071.240000] CPU: 0 PID: 7201 Comm: ux0,1388632927, Not tainted 3.10.24 #18
			# or on kernel 3.3.8:
			# <4>[ 1436.952000] Process uxL,1403754286, (pid: 9633, threadinfo=80446000, task=80cdb978, tls=77691440)
			set -- $line

			while shift; do {
				case "$1 $2" in
					'Comm: ux'*|'Process ux'*)
						reason="$(   echo "$2" | cut -b3 )"
						unixtime="$( echo "$2" | cut -d',' -f2 )"
						break
					;;
					' ')
						break
					;;
				esac
			} done

			date --set @$unixtime
			reason="$( reason_long "$reason" )"
			echo "$( date ) [OK] reboot reason: '$reason'" >>"$PERMLOG"
			echo "$reason" >'/tmp/REBOOT_REASON'
		else
			if [ -e "$crashlog" ]; then
				if   grep -q 'SysRq : Trigger a crash' "$crashlog"; then
					# e.g. in cron.minutely PSWORK()
					# CPU: 0 PID: 28069 Comm: sh Not tainted 3.18.14 #1
					echo "$( date ) [ERROR] emergency_triggered crash detected in '$crashlog'" >>"$PERMLOG"
					echo 'emergency_trigger' >'/tmp/REBOOT_REASON'
				elif grep -q 'device closed unexpectedly, watchdog timer will not stop!' "$crashlog"; then
					echo "$( date ) [ERROR] watchdog action detected in '$crashlog'" >>"$PERMLOG"
					echo 'kernel_watchdog' >'/tmp/REBOOT_REASON'
				elif grep -q ' invoked oom-killer' "$crashlog"; then
					echo "$( date ) [ERROR] oom action detected in '$crashlog'" >>"$PERMLOG"
					echo 'out-of-memory' >'/tmp/REBOOT_REASON'
				else
					echo "$( date ) [ERROR] crash detected in '$crashlog'" >>"$PERMLOG"
					echo "realcrash" >'/tmp/REBOOT_REASON'
				fi
			else
				echo "$( date ) [ERROR] reboot without reason/crash" >>"$PERMLOG"
				echo 'nocrash' >'/tmp/REBOOT_REASON'
			fi
		fi
	else
		reason="$( tail -n1 "$PERMLOG" | grep 'system_crashreboot' | cut -d'=' -f2 )"
		reason="$( reason_long "$reason" )"
		echo "${reason:-nocrash}" >'/tmp/REBOOT_REASON'
		echo "$( date ) (crashlog not working) BOOTUP: reason: ${reason:-nocrash}" >>"$PERMLOG"
	fi

	{
		echo "# [START] $PERMLOG"
		tail -n5 "$PERMLOG"
		echo "# [READY] $PERMLOG"
	} >/dev/console

	touch '/tmp/BOOT'
	touch '/tmp/DEBUG'

	/etc/init.d/kalua_init
	. /tmp/loader

	# e.g. reboot-on-panic
	_system sysctl_tweaks
	_watch counter '/www/REBOOT_COUNTER' increment 1
	sync

	# see scheduler_run()
	touch "$TMPDIR/scheduler_keep_running"
}
