#!/bin/sh /etc/rc.common

START=90

start() {
	[ -n "$FAILSAFE" ] && exit
	[ -e /www/SOFTWARE_FULLY_INSTALLED ] || exit

	# write latlong into file 
	[ -n "$( uci -q get system.@system[0].latitude )" ] && {
	echo "$( uci -q get system.@system[0].latitude ),$( uci -q get system.@system[0].longitude )">/var/run/latlon.txt
	}
	# register first time
   	/usr/sbin/cron.registrator_client.sh
	# draw on map first time
	/usr/sbin/owm.lua
}
