#!/bin/sh
grep -q '^sch_cake' '/proc/modules' || return

case "$ACTION" in
	ifup)
		[ $(awk '/^MemTotal/ {print $2}' < /proc/meminfo) -gt 40000 ] || return
		command -V tc >/dev/null || return 
		tc qdisc replace dev "$DEVICE" root cake
	;;
esac
# vim: set filetype=sh ai noet ts=4 sw=4 sts=4 :
