#!/bin/sh 

[ "$INTERFACE" = "wan" ] && {

	. /usr/lib/weimarnetz/vpn.sh 
 
	case "$ACTION" in 
		ifup) 
			_vpn start
		;;
		ifdown)
			_vpn stop
		;;
	esac
}

# vim: set filetype=sh ai noet ts=4 sw=4 sts=4 :
