#!/bin/sh 

[ "$INTERFACE" = "wan" ] && {

	[ $(uci -q get ffwizard.vpn.enabled) -eq 1 ] || return

	case "$ACTION" in 
		ifup) 
			ifup vpn
		;;
		ifdown)
			ifdown vpn
		;;
	esac
}

[ "$INTERFACE" = "vpn" ] && {
    logger -t vpn_hotplug -p daemon.info "[OK] restart olsrd because of changes in vpn"
	. /etc/rc.common /etc/init.d/olsrd restart
    # no need to set default-gw when in innercity mode
	[ "$(uci -q get ffwizard.vpn.mode)" = "innercity" ] && return

	gw="$(uci -q get network.vpn.gateway)"
	case "$ACTION" in
		ifup)
			ip route add default via $gw table 50
			ip rule add to 10.0.0.0/8 prio 30001 table main		
			ip rule add from 10.63.0.0/16 prio 30010 table 50 
			ip rule add to 100.64.0.1/10 prio 30002 table main
			ip rule add from 100.64.0.1/10 prio 30003 table 50
		;;
		ifdown)
			ip route del default via $gw table 50
			ip rule del to 10.0.0.0/8 prio 30001 table main		
			ip rule del from 10.63.0.0/16 prio 30010 table 50
			ip rule del to 100.64.0.1/10 prio 30002 table main
			ip rule del from 100.64.0.1/10 prio 30003 table 50

		;;
	esac					  
}

# vim: set filetype=sh ai noet ts=4 sw=4 sts=4 :
