#!/bin/sh 

[ "$INTERFACE" = "wan" ] && {

        case "$ACTION" in 
                ifup) 
			nn=$(uci -q get ffwizard.settings.nodenumber)
			[ -z "$nn" ] && registrator create
                ;;
                ifdown)
                ;;
        esac
}
